version: '3'
services: 
  db:
    image: postgres
    environment:
      - POSTGRES_DB=corider
      - POSTGRES_USER=horpeazy
      - POSTGRES_PASSWORD=afisuru123
    volumes:
      - postgres-data:/var/lib/postgresql/data

  test_app:
    image: corider:latest
    environment:
      - DATABASE_NAME=corider
      - DATABASE_USER=horpeazy
      - DATABASE_USER_PWD=afisuru123
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    volumes:
      - /var/www/html/corider/static:/corider/static/
      - /var/www/html/corider/media:/corider/media/
    depends_on:
      - db
    working_dir: /corider
    command: >
      bash -c '
       ./wait-for-it.sh db:5432 -t 60 &&
       python manage.py makemigrations &&
       python manage.py migrate &&
       gunicorn corider.wsgi:application --bind 0.0.0.0:8000 '
      
volumes:
  postgres-data:
    driver: local

