version: '3'
services: 
  db:
    image: postgres
    environment:
      - POSTGRES_DB=corider
      - POSTGRES_USER=horpeazy
      - POSTGRES_PASSWORD=afisuru123
    volumes:
      - postgres-data:/var/lib/postgresql/data
    tty: true
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "horpeazy"]
      interval: 5s
      timeout: 1s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9001:8000
    environment:
      - DATABASE_NAME=corider
      - DATABASE_USER=horpeazy
      - DATABASE_USER_PWD=afisuru123
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    volumes:
      - /var/www/html/corider/static:/corider/static/
      - /var/www/html/corider/media:/corider/media/
    depends_on:
      db:
        condition: service_healthy
    working_dir: /corider
    command: >
      bash -c '
       ./wait-for-it.sh db:5432 -t 60 &&
       python manage.py makemigrations &&
       python manage.py migrate &&
       gunicorn corider.wsgi:application --bind 0.0.0.0:8000 '
    tty: true
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://app:8000']
      interval: 60s
      timeout: 10s
      retries: 5
      
volumes:
  postgres-data:
    driver: local

