# Generated by Django 4.2.1 on 2023-05-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='passengers',
            field=models.ManyToManyField(blank=True, to='rides.ride'),
        ),
    ]
